#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                               0
#define TRAINER_SAWYER_1                           1
#define TRAINER_GABRIELLE_1                        2
#define TRAINER_MARCEL                             3
#define TRAINER_ALBERTO                            4
#define TRAINER_ED                                 5
#define TRAINER_DECLAN                             6
#define TRAINER_FREDRICK                           7
#define TRAINER_ZANDER                             8
#define TRAINER_LEAH                               9
#define TRAINER_DAISY                              10
#define TRAINER_ROSE_1                             11
#define TRAINER_FELIX                              12
#define TRAINER_VIOLET                             13
#define TRAINER_ROSE_2                             14
#define TRAINER_ROSE_3                             15
#define TRAINER_ROSE_4                             16
#define TRAINER_ROSE_5                             17
#define TRAINER_DUSTY_1                            18
#define TRAINER_CHIP                               19
#define TRAINER_FOSTER                             20
#define TRAINER_DUSTY_2                            21
#define TRAINER_DUSTY_3                            22
#define TRAINER_DUSTY_4                            23
#define TRAINER_DUSTY_5                            24
#define TRAINER_GABBY_AND_TY_1                     25
#define TRAINER_GABBY_AND_TY_2                     26
#define TRAINER_GABBY_AND_TY_3                     27
#define TRAINER_GABBY_AND_TY_4                     28
#define TRAINER_GABBY_AND_TY_5                     29
#define TRAINER_GABBY_AND_TY_6                     30
#define TRAINER_LOLA_1                             31
#define TRAINER_AUSTINA                            32
#define TRAINER_GWEN                               33
#define TRAINER_LOLA_2                             34
#define TRAINER_LOLA_3                             35
#define TRAINER_LOLA_4                             36
#define TRAINER_LOLA_5                             37
#define TRAINER_RICKY_1                            38
#define TRAINER_SIMON                              39
#define TRAINER_CHARLIE                            40
#define TRAINER_RICKY_2                            41
#define TRAINER_RICKY_3                            42
#define TRAINER_RICKY_4                            43
#define TRAINER_RICKY_5                            44
#define TRAINER_RANDALL                            45
#define TRAINER_PARKER                             46
#define TRAINER_GEORGE                             47
#define TRAINER_BERKE                              48
#define TRAINER_BRAXTON                            49
#define TRAINER_VINCENT                            50
#define TRAINER_LEROY                              51
#define TRAINER_WILTON_1                           52
#define TRAINER_EDGAR                              53
#define TRAINER_ALBERT                             54
#define TRAINER_SAMUEL                             55
#define TRAINER_VITO                               56
#define TRAINER_OWEN                               57
#define TRAINER_WILTON_2                           58
#define TRAINER_WILTON_3                           59
#define TRAINER_WILTON_4                           60
#define TRAINER_WILTON_5                           61
#define TRAINER_WARREN                             62
#define TRAINER_MARY                               63
#define TRAINER_ALEXIA                             64
#define TRAINER_JODY                               65
#define TRAINER_WENDY                              66
#define TRAINER_KEIRA                              67
#define TRAINER_BROOKE_1                           68
#define TRAINER_JENNIFER                           69
#define TRAINER_HOPE                               70
#define TRAINER_SHANNON                            71
#define TRAINER_MICHELLE                           72
#define TRAINER_CAROLINE                           73
#define TRAINER_JULIE                              74
#define TRAINER_BROOKE_2                           75
#define TRAINER_BROOKE_3                           76
#define TRAINER_BROOKE_4                           77
#define TRAINER_BROOKE_5                           78
#define TRAINER_PATRICIA                           79
#define TRAINER_KINDRA                             80
#define TRAINER_TAMMY                              81
#define TRAINER_VALERIE_1                          82
#define TRAINER_TASHA                              83
#define TRAINER_VALERIE_2                          84
#define TRAINER_VALERIE_3                          85
#define TRAINER_VALERIE_4                          86
#define TRAINER_VALERIE_5                          87
#define TRAINER_CINDY_1                            88
#define TRAINER_DAPHNE                             89
#define TRAINER_CINDY_2                            90
#define TRAINER_BRIANNA                            91
#define TRAINER_NAOMI                              92
#define TRAINER_CINDY_3                            93
#define TRAINER_CINDY_4                            94
#define TRAINER_CINDY_5                            95
#define TRAINER_CINDY_6                            96
#define TRAINER_MELISSA                            97
#define TRAINER_SHEILA                             98
#define TRAINER_SHIRLEY                            99
#define TRAINER_JESSICA_1                          100
#define TRAINER_CONNIE                             101
#define TRAINER_BRIDGET                            102
#define TRAINER_OLIVIA                             103
#define TRAINER_TIFFANY                            104
#define TRAINER_JESSICA_2                          105
#define TRAINER_JESSICA_3                          106
#define TRAINER_JESSICA_4                          107
#define TRAINER_JESSICA_5                          108
#define TRAINER_WINSTON_1                          109
#define TRAINER_MOLLIE                             110
#define TRAINER_GARRET                             111
#define TRAINER_WINSTON_2                          112
#define TRAINER_WINSTON_3                          113
#define TRAINER_WINSTON_4                          114
#define TRAINER_WINSTON_5                          115
#define TRAINER_STEVE_1                            116
#define TRAINER_THALIA_1                           117
#define TRAINER_MARK                               118
#define TRAINER_STEVE_2                            119
#define TRAINER_STEVE_3                            120
#define TRAINER_STEVE_4                            121
#define TRAINER_STEVE_5                            122
#define TRAINER_LUIS                               123
#define TRAINER_DOMINIK                            124
#define TRAINER_DOUGLAS                            125
#define TRAINER_DARRIN                             126
#define TRAINER_TONY_1                             127
#define TRAINER_JEROME                             128
#define TRAINER_MATTHEW                            129
#define TRAINER_DAVID                              130
#define TRAINER_SPENCER                            131
#define TRAINER_ROLAND                             132
#define TRAINER_NOLEN                              133
#define TRAINER_STAN                               134
#define TRAINER_BARRY                              135
#define TRAINER_DEAN                               136
#define TRAINER_RODNEY                             137
#define TRAINER_RICHARD                            138
#define TRAINER_HERMAN                             139
#define TRAINER_SANTIAGO                           140
#define TRAINER_GILBERT                            141
#define TRAINER_FRANKLIN                           142
#define TRAINER_KEVIN                              143
#define TRAINER_JACK                               144
#define TRAINER_DUDLEY                             145
#define TRAINER_CHAD                               146
#define TRAINER_TONY_2                             147
#define TRAINER_TONY_3                             148
#define TRAINER_TONY_4                             149
#define TRAINER_TONY_5                             150
#define TRAINER_TAKAO                              151
#define TRAINER_HITOSHI                            152
#define TRAINER_KIYO                               153
#define TRAINER_KOICHI                             154
#define TRAINER_NOB_1                              155
#define TRAINER_NOB_2                              156
#define TRAINER_NOB_3                              157
#define TRAINER_NOB_4                              158
#define TRAINER_NOB_5                              159
#define TRAINER_YUJI                               160
#define TRAINER_DAISUKE                            161
#define TRAINER_ATSUSHI                            162
#define TRAINER_KIRK                               163
#define TRAINER_SHAWN                              164
#define TRAINER_FERNANDO_1                         165
#define TRAINER_DALTON_1                           166
#define TRAINER_DALTON_2                           167
#define TRAINER_DALTON_3                           168
#define TRAINER_DALTON_4                           169
#define TRAINER_DALTON_5                           170
#define TRAINER_COLE                               171
#define TRAINER_JEFF                               172
#define TRAINER_AXLE                               173
#define TRAINER_JACE                               174
#define TRAINER_KEEGAN                             175
#define TRAINER_BERNIE_1                           176
#define TRAINER_BERNIE_2                           177
#define TRAINER_BERNIE_3                           178
#define TRAINER_BERNIE_4                           179
#define TRAINER_BERNIE_5                           180
#define TRAINER_DREW                               181
#define TRAINER_BEAU                               182
#define TRAINER_LARRY                              183
#define TRAINER_SHANE                              184
#define TRAINER_JUSTIN                             185
#define TRAINER_ETHAN_1                            186
#define TRAINER_AUTUMN                             187
#define TRAINER_TRAVIS                             188
#define TRAINER_ETHAN_2                            189
#define TRAINER_ETHAN_3                            190
#define TRAINER_ETHAN_4                            191
#define TRAINER_ETHAN_5                            192
#define TRAINER_BRENT                              193
#define TRAINER_DONALD                             194
#define TRAINER_TAYLOR                             195
#define TRAINER_JEFFREY_1                          196
#define TRAINER_DEREK                              197
#define TRAINER_JEFFREY_2                          198
#define TRAINER_JEFFREY_3                          199
#define TRAINER_JEFFREY_4                          200
#define TRAINER_JEFFREY_5                          201
#define TRAINER_EDWARD                             202
#define TRAINER_PRESTON                            203
#define TRAINER_VIRGIL                             204
#define TRAINER_BLAKE                              205
#define TRAINER_WILLIAM                            206
#define TRAINER_JOSHUA                             207
#define TRAINER_CAMERON_1                          208
#define TRAINER_CAMERON_2                          209
#define TRAINER_CAMERON_3                          210
#define TRAINER_CAMERON_4                          211
#define TRAINER_CAMERON_5                          212
#define TRAINER_JACLYN                             213
#define TRAINER_HANNAH                             214
#define TRAINER_SAMANTHA                           215
#define TRAINER_MAURA                              216
#define TRAINER_KAYLA                              217
#define TRAINER_ALEXIS                             218
#define TRAINER_JACKI_1                            219
#define TRAINER_JACKI_2                            220
#define TRAINER_JACKI_3                            221
#define TRAINER_JACKI_4                            222
#define TRAINER_JACKI_5                            223
#define TRAINER_WALTER_1                           224
#define TRAINER_MICAH                              225
#define TRAINER_THOMAS                             226
#define TRAINER_WALTER_2                           227
#define TRAINER_WALTER_3                           228
#define TRAINER_WALTER_4                           229
#define TRAINER_WALTER_5                           230
#define TRAINER_SIDNEY                             231
#define TRAINER_PHOEBE                             232
#define TRAINER_GLACIA                             233
#define TRAINER_DRAKE                              234
#define TRAINER_ROXANNE_1                          235
#define TRAINER_BRAWLY_1                           236
#define TRAINER_WATTSON_1                          237
#define TRAINER_FLANNERY_1                         238
#define TRAINER_NORMAN_1                           239
#define TRAINER_WINONA_1                           240
#define TRAINER_TATE_AND_LIZA_1                    241
#define TRAINER_JUAN_1                             242
#define TRAINER_JERRY_1                            243
#define TRAINER_TED                                244
#define TRAINER_PAUL                               245
#define TRAINER_JERRY_2                            246
#define TRAINER_JERRY_3                            247
#define TRAINER_JERRY_4                            248
#define TRAINER_JERRY_5                            249
#define TRAINER_KAREN_1                            250
#define TRAINER_GEORGIA                            251
#define TRAINER_KAREN_2                            252
#define TRAINER_KAREN_3                            253
#define TRAINER_KAREN_4                            254
#define TRAINER_KAREN_5                            255
#define TRAINER_KATE_AND_JOY                       256
#define TRAINER_ANNA_AND_MEG_1                     257
#define TRAINER_ANNA_AND_MEG_2                     258
#define TRAINER_ANNA_AND_MEG_3                     259
#define TRAINER_ANNA_AND_MEG_4                     260
#define TRAINER_ANNA_AND_MEG_5                     261
#define TRAINER_VICTOR                             262
#define TRAINER_MIGUEL_1                           263
#define TRAINER_COLTON                             264
#define TRAINER_MIGUEL_2                           265
#define TRAINER_MIGUEL_3                           266
#define TRAINER_MIGUEL_4                           267
#define TRAINER_MIGUEL_5                           268
#define TRAINER_VICTORIA                           269
#define TRAINER_VANESSA                            270
#define TRAINER_BETHANY                            271
#define TRAINER_ISABEL_1                           272
#define TRAINER_ISABEL_2                           273
#define TRAINER_ISABEL_3                           274
#define TRAINER_ISABEL_4                           275
#define TRAINER_ISABEL_5                           276
#define TRAINER_TIMOTHY_1                          277
#define TRAINER_TIMOTHY_2                          278
#define TRAINER_TIMOTHY_3                          279
#define TRAINER_TIMOTHY_4                          280
#define TRAINER_TIMOTHY_5                          281
#define TRAINER_VICKY                              282
#define TRAINER_SHELBY_1                           283
#define TRAINER_SHELBY_2                           284
#define TRAINER_SHELBY_3                           285
#define TRAINER_SHELBY_4                           286
#define TRAINER_SHELBY_5                           287
#define TRAINER_CALVIN_1                           288
#define TRAINER_BILLY                              289
#define TRAINER_JOSH                               290
#define TRAINER_TOMMY                              291
#define TRAINER_JOEY                               292
#define TRAINER_BEN                                293
#define TRAINER_QUINCY                             294
#define TRAINER_KATELYNN                           295
#define TRAINER_JAYLEN                             296
#define TRAINER_DILLON                             297
#define TRAINER_CALVIN_2                           298
#define TRAINER_CALVIN_3                           299
#define TRAINER_CALVIN_4                           300
#define TRAINER_CALVIN_5                           301
#define TRAINER_EDDIE                              302
#define TRAINER_ALLEN                              303
#define TRAINER_TIMMY                              304
#define TRAINER_WALLACE                            305
#define TRAINER_ANDREW                             306
#define TRAINER_IVAN                               307
#define TRAINER_CLAUDE                             308
#define TRAINER_ELLIOT_1                           309
#define TRAINER_NED                                310
#define TRAINER_DALE                               311
#define TRAINER_NOLAN                              312
#define TRAINER_BARNY                              313
#define TRAINER_WADE                               314
#define TRAINER_CARTER                             315
#define TRAINER_ELLIOT_2                           316
#define TRAINER_ELLIOT_3                           317
#define TRAINER_ELLIOT_4                           318
#define TRAINER_ELLIOT_5                           319
#define TRAINER_RONALD                             320
#define TRAINER_JACOB                              321
#define TRAINER_ANTHONY                            322
#define TRAINER_BENJAMIN_1                         323
#define TRAINER_BENJAMIN_2                         324
#define TRAINER_BENJAMIN_3                         325
#define TRAINER_BENJAMIN_4                         326
#define TRAINER_BENJAMIN_5                         327
#define TRAINER_ABIGAIL_1                          328
#define TRAINER_JASMINE                            329
#define TRAINER_ABIGAIL_2                          330
#define TRAINER_ABIGAIL_3                          331
#define TRAINER_ABIGAIL_4                          332
#define TRAINER_ABIGAIL_5                          333
#define TRAINER_DYLAN_1                            334
#define TRAINER_DYLAN_2                            335
#define TRAINER_DYLAN_3                            336
#define TRAINER_DYLAN_4                            337
#define TRAINER_DYLAN_5                            338
#define TRAINER_MARIA_1                            339
#define TRAINER_MARIA_2                            340
#define TRAINER_MARIA_3                            341
#define TRAINER_MARIA_4                            342
#define TRAINER_MARIA_5                            343
#define TRAINER_CAMDEN                             344
#define TRAINER_DEMETRIUS                          345
#define TRAINER_ISAIAH_1                           346
#define TRAINER_PABLO_1                            347
#define TRAINER_CHASE                              348
#define TRAINER_ISAIAH_2                           349
#define TRAINER_ISAIAH_3                           350
#define TRAINER_ISAIAH_4                           351
#define TRAINER_ISAIAH_5                           352
#define TRAINER_ISOBEL                             353
#define TRAINER_DONNY                              354
#define TRAINER_TALIA                              355
#define TRAINER_KATELYN_1                          356
#define TRAINER_ALLISON                            357
#define TRAINER_KATELYN_2                          358
#define TRAINER_KATELYN_3                          359
#define TRAINER_KATELYN_4                          360
#define TRAINER_KATELYN_5                          361
#define TRAINER_NICOLAS_1                          362
#define TRAINER_NICOLAS_2                          363
#define TRAINER_NICOLAS_3                          364
#define TRAINER_NICOLAS_4                          365
#define TRAINER_NICOLAS_5                          366
#define TRAINER_AARON                              367
#define TRAINER_PERRY                              368
#define TRAINER_HUGH                               369
#define TRAINER_PHIL                               370
#define TRAINER_JARED                              371
#define TRAINER_HUMBERTO                           372
#define TRAINER_PRESLEY                            373
#define TRAINER_EDWARDO                            374
#define TRAINER_COLIN                              375
#define TRAINER_ROBERT_1                           376
#define TRAINER_BENNY                              377
#define TRAINER_CHESTER                            378
#define TRAINER_ROBERT_2                           379
#define TRAINER_ROBERT_3                           380
#define TRAINER_ROBERT_4                           381
#define TRAINER_ROBERT_5                           382
#define TRAINER_ALEX                               383
#define TRAINER_BECK                               384
#define TRAINER_YASU                               385
#define TRAINER_TAKASHI                            386
#define TRAINER_DIANNE                             387
#define TRAINER_JANI                               388
#define TRAINER_LAO_1                              389
#define TRAINER_LUNG                               390
#define TRAINER_LAO_2                              391
#define TRAINER_LAO_3                              392
#define TRAINER_LAO_4                              393
#define TRAINER_LAO_5                              394
#define TRAINER_JOCELYN                            395
#define TRAINER_LAURA                              396
#define TRAINER_CYNDY_1                            397
#define TRAINER_CORA                               398
#define TRAINER_PAULA                              399
#define TRAINER_CYNDY_2                            400
#define TRAINER_CYNDY_3                            401
#define TRAINER_CYNDY_4                            402
#define TRAINER_CYNDY_5                            403
#define TRAINER_MADELINE_1                         404
#define TRAINER_CLARISSA                           405
#define TRAINER_ANGELICA                           406
#define TRAINER_MADELINE_2                         407
#define TRAINER_MADELINE_3                         408
#define TRAINER_MADELINE_4                         409
#define TRAINER_MADELINE_5                         410
#define TRAINER_BEVERLY                            411
#define TRAINER_IMANI                              412
#define TRAINER_KYLA                               413
#define TRAINER_DENISE                             414
#define TRAINER_BETH                               415
#define TRAINER_TARA                               416
#define TRAINER_MISSY                              417
#define TRAINER_ALICE                              418
#define TRAINER_JENNY_1                            419
#define TRAINER_GRACE                              420
#define TRAINER_TANYA                              421
#define TRAINER_SHARON                             422
#define TRAINER_NIKKI                              423
#define TRAINER_BRENDA                             424
#define TRAINER_KATIE                              425
#define TRAINER_SUSIE                              426
#define TRAINER_KARA                               427
#define TRAINER_DANA                               428
#define TRAINER_SIENNA                             429
#define TRAINER_DEBRA                              430
#define TRAINER_LINDA                              431
#define TRAINER_KAYLEE                             432
#define TRAINER_LAUREL                             433
#define TRAINER_CARLEE                             434
#define TRAINER_JENNY_2                            435
#define TRAINER_JENNY_3                            436
#define TRAINER_JENNY_4                            437
#define TRAINER_JENNY_5                            438
#define TRAINER_HEIDI                              439
#define TRAINER_BECKY                              440
#define TRAINER_CAROL                              441
#define TRAINER_NANCY                              442
#define TRAINER_MARTHA                             443
#define TRAINER_DIANA_1                            444
#define TRAINER_CEDRIC                             445
#define TRAINER_IRENE                              446
#define TRAINER_DIANA_2                            447
#define TRAINER_DIANA_3                            448
#define TRAINER_DIANA_4                            449
#define TRAINER_DIANA_5                            450
#define TRAINER_AMY_AND_LIV_1                      451
#define TRAINER_AMY_AND_LIV_2                      452
#define TRAINER_GINA_AND_MIA_1                     453
#define TRAINER_MIU_AND_YUKI                       454
#define TRAINER_AMY_AND_LIV_3                      455
#define TRAINER_GINA_AND_MIA_2                     456
#define TRAINER_AMY_AND_LIV_4                      457
#define TRAINER_AMY_AND_LIV_5                      458
#define TRAINER_AMY_AND_LIV_6                      459
#define TRAINER_HUEY                               460
#define TRAINER_EDMOND                             461
#define TRAINER_ERNEST_1                           462
#define TRAINER_DWAYNE                             463
#define TRAINER_PHILLIP                            464
#define TRAINER_LEONARD                            465
#define TRAINER_DUNCAN                             466
#define TRAINER_ERNEST_2                           467
#define TRAINER_ERNEST_3                           468
#define TRAINER_ERNEST_4                           469
#define TRAINER_ERNEST_5                           470
#define TRAINER_ELI                                471
#define TRAINER_ANNIKA                             472
#define TRAINER_JAZMYN                             473
#define TRAINER_JONAS                              474
#define TRAINER_KAYLEY                             475
#define TRAINER_AURON                              476
#define TRAINER_KELVIN                             477
#define TRAINER_MARLEY                             478
#define TRAINER_REYNA                              479
#define TRAINER_HUDSON                             480
#define TRAINER_CONOR                              481
#define TRAINER_EDWIN_1                            482
#define TRAINER_HECTOR                             483
#define TRAINER_EDWIN_2                            484
#define TRAINER_EDWIN_3                            485
#define TRAINER_EDWIN_4                            486
#define TRAINER_EDWIN_5                            487
#define TRAINER_GOLD_ROUTE_29                      488
#define TRAINER_BRENDAN_ROUTE_103                  489
#define TRAINER_LYRA_ROUTE_29                      490
#define TRAINER_MAY_ROUTE_103                      491
#define TRAINER_ISAAC_1                            492
#define TRAINER_DAVIS                              493
#define TRAINER_MITCHELL                           494
#define TRAINER_ISAAC_2                            495
#define TRAINER_ISAAC_3                            496
#define TRAINER_ISAAC_4                            497
#define TRAINER_ISAAC_5                            498
#define TRAINER_LYDIA_1                            499
#define TRAINER_HALLE                              500
#define TRAINER_GARRISON                           501
#define TRAINER_LYDIA_2                            502
#define TRAINER_LYDIA_3                            503
#define TRAINER_LYDIA_4                            504
#define TRAINER_LYDIA_5                            505
#define TRAINER_JACKSON_1                          506
#define TRAINER_LORENZO                            507
#define TRAINER_SEBASTIAN                          508
#define TRAINER_JACKSON_2                          509
#define TRAINER_JACKSON_3                          510
#define TRAINER_JACKSON_4                          511
#define TRAINER_JACKSON_5                          512
#define TRAINER_CATHERINE_1                        513
#define TRAINER_JENNA                              514
#define TRAINER_SOPHIA                             515
#define TRAINER_CATHERINE_2                        516
#define TRAINER_CATHERINE_3                        517
#define TRAINER_CATHERINE_4                        518
#define TRAINER_CATHERINE_5                        519
#define TRAINER_JULIO                              520
#define TRAINER_MARC                               521
#define TRAINER_BRENDEN                            522
#define TRAINER_LILITH                             523
#define TRAINER_CRISTIAN                           524
#define TRAINER_SYLVIA                             525
#define TRAINER_LEONARDO                           526
#define TRAINER_ATHENA                             527
#define TRAINER_HARRISON                           528
#define TRAINER_CLARENCE                           529
#define TRAINER_TERRY                              530
#define TRAINER_NATE                               531
#define TRAINER_KATHLEEN                           532
#define TRAINER_CLIFFORD                           533
#define TRAINER_NICHOLAS                           534
#define TRAINER_MACEY                              535
#define TRAINER_PAXTON                             536
#define TRAINER_ISABELLA                           537
#define TRAINER_JONATHAN                           538
#define TRAINER_TIANA                              539
#define TRAINER_HALEY_1                            540
#define TRAINER_JANICE                             541
#define TRAINER_VIVI                               542
#define TRAINER_HALEY_2                            543
#define TRAINER_HALEY_3                            544
#define TRAINER_HALEY_4                            545
#define TRAINER_HALEY_5                            546
#define TRAINER_SALLY                              547
#define TRAINER_ROBIN                              548
#define TRAINER_ANDREA                             549
#define TRAINER_CRISSY                             550
#define TRAINER_RICK                               551
#define TRAINER_LYLE                               552
#define TRAINER_JOSE                               553
#define TRAINER_DOUG                               554
#define TRAINER_GREG                               555
#define TRAINER_KENT                               556
#define TRAINER_JAMES_1                            557
#define TRAINER_JAMES_2                            558
#define TRAINER_JAMES_3                            559
#define TRAINER_JAMES_4                            560
#define TRAINER_JAMES_5                            561
#define TRAINER_BRICE                              562
#define TRAINER_TRENT_1                            563
#define TRAINER_LENNY                              564
#define TRAINER_LUCAS_1                            565
#define TRAINER_ALAN                               566
#define TRAINER_CLARK                              567
#define TRAINER_ERIC                               568
#define TRAINER_LUCAS_2                            569
#define TRAINER_MIKE_1                             570
#define TRAINER_MIKE_2                             571
#define TRAINER_TRENT_2                            572
#define TRAINER_TRENT_3                            573
#define TRAINER_TRENT_4                            574
#define TRAINER_TRENT_5                            575
#define TRAINER_DEZ_AND_LUKE                       576
#define TRAINER_LEA_AND_JED                        577
#define TRAINER_KIRA_AND_DAN_1                     578
#define TRAINER_KIRA_AND_DAN_2                     579
#define TRAINER_KIRA_AND_DAN_3                     580
#define TRAINER_KIRA_AND_DAN_4                     581
#define TRAINER_KIRA_AND_DAN_5                     582
#define TRAINER_JOHANNA                            583
#define TRAINER_GERALD                             584
#define TRAINER_VIVIAN                             585
#define TRAINER_DANIELLE                           586
#define TRAINER_HIDEO                              587
#define TRAINER_KEIGO                              588
#define TRAINER_RILEY                              589
#define TRAINER_FLINT                              590
#define TRAINER_ASHLEY                             591
#define TRAINER_WALLY_VR_2                         592
#define TRAINER_WALLY_VR_3                         593
#define TRAINER_WALLY_VR_4                         594
#define TRAINER_WALLY_VR_5                         595
#define TRAINER_JONAH                              596
#define TRAINER_HENRY                              597
#define TRAINER_ROGER                              598
#define TRAINER_ALEXA                              599
#define TRAINER_RUBEN                              600
#define TRAINER_KOJI_1                             601
#define TRAINER_WAYNE                              602
#define TRAINER_AIDAN                              603
#define TRAINER_REED                               604
#define TRAINER_TISHA                              605
#define TRAINER_TORI_AND_TIA                       606
#define TRAINER_KIM_AND_IRIS                       607
#define TRAINER_TYRA_AND_IVY                       608
#define TRAINER_MEL_AND_PAUL                       609
#define TRAINER_JOHN_AND_JAY_1                     610
#define TRAINER_JOHN_AND_JAY_2                     611
#define TRAINER_JOHN_AND_JAY_3                     612
#define TRAINER_JOHN_AND_JAY_4                     613
#define TRAINER_JOHN_AND_JAY_5                     614
#define TRAINER_RELI_AND_IAN                       615
#define TRAINER_LILA_AND_ROY_1                     616
#define TRAINER_LILA_AND_ROY_2                     617
#define TRAINER_LILA_AND_ROY_3                     618
#define TRAINER_LILA_AND_ROY_4                     619
#define TRAINER_LILA_AND_ROY_5                     620
#define TRAINER_LISA_AND_RAY                       621
#define TRAINER_CHRIS                              622
#define TRAINER_DAWSON                             623
#define TRAINER_SARAH                              624
#define TRAINER_DARIAN                             625
#define TRAINER_HAILEY                             626
#define TRAINER_CHANDLER                           627
#define TRAINER_KALEB                              628
#define TRAINER_JOSEPH                             629
#define TRAINER_ALYSSA                             630
#define TRAINER_MARCOS                             631
#define TRAINER_RHETT                              632
#define TRAINER_TYRON                              633
#define TRAINER_CELINA                             634
#define TRAINER_BIANCA                             635
#define TRAINER_HAYDEN                             636
#define TRAINER_SOPHIE                             637
#define TRAINER_COBY                               638
#define TRAINER_LAWRENCE                           639
#define TRAINER_WYATT                              640
#define TRAINER_ANGELINA                           641
#define TRAINER_KAI                                642
#define TRAINER_CHARLOTTE                          643
#define TRAINER_DEANDRE                            644
#define TRAINER_DARCY                              645
#define TRAINER_PETE                               646
#define TRAINER_ISABELLE                           647
#define TRAINER_ANDRES_1                           648
#define TRAINER_JOSUE                              649
#define TRAINER_CAMRON                             650
#define TRAINER_CORY_1                             651
#define TRAINER_CAROLINA                           652
#define TRAINER_ELIJAH                             653
#define TRAINER_CELIA                              654
#define TRAINER_BRYAN                              655
#define TRAINER_BRANDEN                            656
#define TRAINER_BRYANT                             657
#define TRAINER_SHAYLA                             658
#define TRAINER_KYRA                               659
#define TRAINER_JAIDEN                             660
#define TRAINER_ALIX                               661
#define TRAINER_HELENE                             662
#define TRAINER_MARLENE                            663
#define TRAINER_DEVAN                              664
#define TRAINER_JOHNSON                            665
#define TRAINER_MELINA                             666
#define TRAINER_BRANDI                             667
#define TRAINER_AISHA                              668
#define TRAINER_MAKAYLA                            669
#define TRAINER_FABIAN                             670
#define TRAINER_DAYTON                             671
#define TRAINER_RACHEL                             672
#define TRAINER_LEONEL                             673
#define TRAINER_CALLIE                             674
#define TRAINER_CALE                               675
#define TRAINER_MYLES                              676
#define TRAINER_PAT                                677
#define TRAINER_CRISTIN_1                          678
#define TRAINER_ROXANNE_2                          679
#define TRAINER_ROXANNE_3                          680
#define TRAINER_ROXANNE_4                          681
#define TRAINER_ROXANNE_5                          682
#define TRAINER_BRAWLY_2                           683
#define TRAINER_BRAWLY_3                           684
#define TRAINER_BRAWLY_4                           685
#define TRAINER_BRAWLY_5                           686
#define TRAINER_WATTSON_2                          687
#define TRAINER_WATTSON_3                          688
#define TRAINER_WATTSON_4                          689
#define TRAINER_WATTSON_5                          690
#define TRAINER_FLANNERY_2                         691
#define TRAINER_FLANNERY_3                         692
#define TRAINER_FLANNERY_4                         693
#define TRAINER_FLANNERY_5                         694
#define TRAINER_NORMAN_2                           695
#define TRAINER_NORMAN_3                           696
#define TRAINER_NORMAN_4                           697
#define TRAINER_NORMAN_5                           698
#define TRAINER_WINONA_2                           699
#define TRAINER_WINONA_3                           700
#define TRAINER_WINONA_4                           701
#define TRAINER_WINONA_5                           702
#define TRAINER_TATE_AND_LIZA_2                    703
#define TRAINER_TATE_AND_LIZA_3                    704
#define TRAINER_TATE_AND_LIZA_4                    705
#define TRAINER_TATE_AND_LIZA_5                    706
#define TRAINER_JUAN_2                             707
#define TRAINER_JUAN_3                             708
#define TRAINER_JUAN_4                             709
#define TRAINER_JUAN_5                             710
#define TRAINER_ANGELO                             711
#define TRAINER_DARIUS                             712
#define TRAINER_STEVEN                             713
#define TRAINER_ANABEL                             714
#define TRAINER_TUCKER                             715
#define TRAINER_SPENSER                            716
#define TRAINER_GRETA                              717
#define TRAINER_NOLAND                             718
#define TRAINER_LUCY                               719
#define TRAINER_BRANDON                            720
#define TRAINER_ANDRES_2                           721
#define TRAINER_ANDRES_3                           722
#define TRAINER_ANDRES_4                           723
#define TRAINER_ANDRES_5                           724
#define TRAINER_CORY_2                             725
#define TRAINER_CORY_3                             726
#define TRAINER_CORY_4                             727
#define TRAINER_CORY_5                             728
#define TRAINER_PABLO_2                            729
#define TRAINER_PABLO_3                            730
#define TRAINER_PABLO_4                            731
#define TRAINER_PABLO_5                            732
#define TRAINER_KOJI_2                             733
#define TRAINER_KOJI_3                             734
#define TRAINER_KOJI_4                             735
#define TRAINER_KOJI_5                             736
#define TRAINER_CRISTIN_2                          737
#define TRAINER_CRISTIN_3                          738
#define TRAINER_CRISTIN_4                          739
#define TRAINER_CRISTIN_5                          740
#define TRAINER_FERNANDO_2                         741
#define TRAINER_FERNANDO_3                         742
#define TRAINER_FERNANDO_4                         743
#define TRAINER_FERNANDO_5                         744
#define TRAINER_SAWYER_2                           745
#define TRAINER_SAWYER_3                           746
#define TRAINER_SAWYER_4                           747
#define TRAINER_SAWYER_5                           748
#define TRAINER_GABRIELLE_2                        749
#define TRAINER_GABRIELLE_3                        750
#define TRAINER_GABRIELLE_4                        751
#define TRAINER_GABRIELLE_5                        752
#define TRAINER_THALIA_2                           753
#define TRAINER_THALIA_3                           754
#define TRAINER_THALIA_4                           755
#define TRAINER_THALIA_5                           756
#define TRAINER_MARIELA                            757
#define TRAINER_ALVARO                             758
#define TRAINER_EVERETT                            759
#define TRAINER_RED                                760
#define TRAINER_LEAF                               761
#define TRAINER_BRENDAN_PLACEHOLDER                762
#define TRAINER_MAY_PLACEHOLDER                    763

// Kanto and Johto gym trainers
#define TRAINER_GYM_PEWTER_BROCK                   764
#define TRAINER_GYM_PEWTER_RUSSELL                 765
#define TRAINER_GYM_PEWTER_MASON                   766
#define TRAINER_GYM_PEWTER_ELI                     767
#define TRAINER_GYM_CELADON_ERIKA                  768
#define TRAINER_GYM_CELADON_LILA                   769
#define TRAINER_GYM_CELADON_DAPHNE                 770
#define TRAINER_GYM_CELADON_MIRA                   771
#define TRAINER_GYM_CELADON_SAGE                   772
#define TRAINER_GYM_CELADON_IVY                    773
#define TRAINER_GYM_CELADON_HELENA                 774
#define TRAINER_GYM_CELADON_WILLOW                 775
#define TRAINER_GYM_CELADON_TESSA                  776
#define TRAINER_GYM_VERMILION_SURGE                777
#define TRAINER_GYM_VERMILION_AMOS                 778
#define TRAINER_GYM_VERMILION_CYRUS                779
#define TRAINER_GYM_VERMILION_GIDEON               780
#define TRAINER_GYM_VERMILION_ORSON                781
#define TRAINER_GYM_VERMILION_REID                 782
#define TRAINER_GYM_FUCHSIA_KOGA                   783
#define TRAINER_GYM_FUCHSIA_VEDA                   784
#define TRAINER_GYM_FUCHSIA_KIRI                   785
#define TRAINER_GYM_FUCHSIA_SORREL                 786
#define TRAINER_GYM_FUCHSIA_DORIAN                 787
#define TRAINER_GYM_FUCHSIA_PAX                    788
#define TRAINER_GYM_FUCHSIA_RYU                    789
#define TRAINER_GYM_FUCHSIA_SILAS                  790
#define TRAINER_GYM_CERULEAN_MISTY                 791
#define TRAINER_GYM_CERULEAN_MARINA                792
#define TRAINER_GYM_CERULEAN_FINN                  793
#define TRAINER_GYM_CERULEAN_KELLAN                794
#define TRAINER_GYM_CERULEAN_BOYD                  795
#define TRAINER_GYM_CERULEAN_LUCA                  796
#define TRAINER_GYM_CERULEAN_NIXIE                 797
#define TRAINER_GYM_SAFFRON_SABRINA                798
#define TRAINER_GYM_SAFFRON_NIKO_VIVI              799
#define TRAINER_GYM_SAFFRON_ANSEL                  800
#define TRAINER_GYM_SAFFRON_IRENE_OWEN             801
#define TRAINER_GYM_SAFFRON_VERA                   802
#define TRAINER_GYM_SAFFRON_QUENTIN                803
#define TRAINER_GYM_SAFFRON_NIA_SAUL               804
#define TRAINER_GYM_SAFFRON_FELIX_COR              805
#define TRAINER_GYM_VIOLET_BUGSY                   806
#define TRAINER_GYM_VIOLET_NED                     807
#define TRAINER_GYM_VIOLET_PIP                     808
#define TRAINER_GYM_VIOLET_BRIA                    809
#define TRAINER_GYM_VIOLET_MOSS                    810
#define TRAINER_GYM_ECRUTEAK_MORTY                 811
#define TRAINER_GYM_ECRUTEAK_GALEN_1               812
#define TRAINER_GYM_ECRUTEAK_GALEN_2               813
#define TRAINER_GYM_ECRUTEAK_GALEN_3               814
#define TRAINER_GYM_ECRUTEAK_GALEN_4               815
#define TRAINER_GYM_ECRUTEAK_GALEN_5               816
#define TRAINER_GYM_ECRUTEAK_GALEN_6               817
#define TRAINER_GYM_ECRUTEAK_GALEN_7               818
#define TRAINER_GYM_OLIVINE_JASMINE                819
#define TRAINER_GYM_OLIVINE_SABLE                  820
#define TRAINER_GYM_OLIVINE_PERCIVAL               821
#define TRAINER_GYM_OLIVINE_MYRA                   822
#define TRAINER_GYM_OLIVINE_GARRICK                823
#define TRAINER_GYM_OLIVINE_ADEL_LINN              824
#define TRAINER_GYM_CIANWOOD_CHUCK                 825
#define TRAINER_GYM_CIANWOOD_BAIRD                 826
#define TRAINER_GYM_CIANWOOD_KNOX                  827
#define TRAINER_GYM_CIANWOOD_KENTO                 828
#define TRAINER_GYM_CIANWOOD_MARIS                 829
#define TRAINER_GYM_CIANWOOD_DAX                   830
#define TRAINER_GYM_GOLDENROD_FALKNER              831
#define TRAINER_GYM_GOLDENROD_TAMSIN               832
#define TRAINER_GYM_GOLDENROD_ELARA                833
#define TRAINER_GYM_GOLDENROD_CATO                 834
#define TRAINER_GYM_GOLDENROD_REN                  835
#define TRAINER_GYM_GOLDENROD_VOLKER               836
#define TRAINER_GYM_GOLDENROD_NOLA                 837
#define TRAINER_GYM_GOLDENROD_FLYNN                838
#define TRAINER_GYM_GOLDENROD_MABEL                839
#define TRAINER_GYM_GOLDENROD_ARVID                840
#define TRAINER_GYM_GOLDENROD_SELENE               841
#define TRAINER_GYM_GOLDENROD_IVO                  842
#define TRAINER_GYM_BLACKTHORN_CLAIR               843
#define TRAINER_GYM_BLACKTHORN_GORO                844
#define TRAINER_GYM_BLACKTHORN_ELDON               845
#define TRAINER_GYM_BLACKTHORN_ALINA               846
#define TRAINER_GYM_BLACKTHORN_PETRA               847
#define TRAINER_GYM_BLACKTHORN_MAGNUS              848
#define TRAINER_GYM_BLACKTHORN_CELESTE             849
#define TRAINER_GYM_BLACKTHORN_RHEA                850
#define TRAINER_GYM_BLACKTHORN_TORIN               851
#define TRAINER_GYM_BLACKTHORN_DELLA               852
#define TRAINER_GYM_BLACKTHORN_VANCE               853
#define TRAINER_GYM_BLACKTHORN_IDRIS               854
// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
